#!/usr/bin/env python3
"""
Fix Xevious color palettes - matches MAME's xevious_vh_convert_color_prom exactly.

Based on verified MAME source (mame4all vidhrdw/xevious.cpp):

Palette:
  - 128 actual colors from R=xvi-8.6a, G=xvi-9.6d, B=xvi-10.6e (first 128 bytes each)
  - Color index 128 = transparent (black)
  - Weights: bit0=0x0E, bit1=0x1F, bit2=0x43, bit3=0x8F

BG tiles (128 groups x 4 colors):
  - Lookup: (xvi-7.4h[i] & 0x0F) | ((xvi-6.4f[i] & 0x0F) << 4) -> palette index
  - xvi-7.4h = "bg tiles lookup table LOW"  (512 bytes)
  - xvi-6.4f = "bg tiles lookup table HIGH" (512 bytes)

Sprites (64 groups x 8 colors, 3bpp):
  - Lookup: (xvi-4.3l[i] & 0x0F) | ((xvi-5.3m[i] & 0x0F) << 4)
  - If result bit 7 set: visible, palette = result & 0x7F
  - If result bit 7 clear: transparent (color = 0)
  - xvi-4.3l = "sprite lookup table LOW"  (512 bytes)
  - xvi-5.3m = "sprite lookup table HIGH" (512 bytes)
  - 64 groups x 8 entries = 512 entries (uses all 512 PROM bytes)

FG chars (64 groups x 4 colors):
  - NO PROM lookup! Direct mapping: color_group -> palette[group]
  - Pixel 0 = transparent, pixels 1/2/3 = palette[color_group]

Output format: big-endian RGB565 (pre-swapped for SPI, arcadeUpscaleRow does bswap16).
"""
import os, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
ROM_DIR = os.path.join(PROJECT_ROOT, "ARCADE_ROMS_SD", "xevios")
HDR_DIR = os.path.join(PROJECT_ROOT, "arcade", "machines", "xevious")

def read_rom(name):
    path = os.path.join(ROM_DIR, name)
    with open(path, "rb") as f:
        return f.read()

def decode_color(r_byte, g_byte, b_byte):
    """Decode one palette entry to big-endian RGB565.
    MAME weights: bit0=0x0E, bit1=0x1F, bit2=0x43, bit3=0x8F."""
    r8 = 0x0e*(r_byte&1) + 0x1f*((r_byte>>1)&1) + 0x43*((r_byte>>2)&1) + 0x8f*((r_byte>>3)&1)
    g8 = 0x0e*(g_byte&1) + 0x1f*((g_byte>>1)&1) + 0x43*((g_byte>>2)&1) + 0x8f*((g_byte>>3)&1)
    b8 = 0x0e*(b_byte&1) + 0x1f*((b_byte>>1)&1) + 0x43*((b_byte>>2)&1) + 0x8f*((b_byte>>3)&1)
    r5 = (r8 >> 3) & 0x1F
    g6 = (g8 >> 2) & 0x3F
    b5 = (b8 >> 3) & 0x1F
    rgb565 = (r5 << 11) | (g6 << 5) | b5
    # Convert to big-endian for SPI display (arcadeUpscaleRow does bswap16)
    return ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)

def main():
    # Read PROMs
    r_prom   = read_rom("xvi-8.6a")       # 256 bytes: R component
    g_prom   = read_rom("xvi-9.6d")       # 256 bytes: G component
    b_prom   = read_rom("xvi-10.6e")      # 256 bytes: B component
    bg_lo    = read_rom("xvi-7.4h")       # 512 bytes: BG tiles lookup LOW
    bg_hi    = read_rom("xvi-6.4f")       # 512 bytes: BG tiles lookup HIGH
    spr_lo   = read_rom("xvi-4.3l")       # 512 bytes: sprite lookup LOW
    spr_hi   = read_rom("xvi-5.3m")       # 512 bytes: sprite lookup HIGH
    sr3_data = read_rom("xvi-1.5n")       # 256 bytes: B800-B8FF PROM

    # === Generate 128-entry palette (matching MAME exactly) ===
    palette = [0] * 128
    for i in range(128):
        palette[i] = decode_color(r_prom[i], g_prom[i], b_prom[i])

    # Print palette samples for verification
    print("=== Palette samples (128 colors) ===")
    for idx in [0, 1, 2, 3, 4, 5, 10, 20, 30, 60, 63, 100, 127]:
        v = palette[idx]
        le = ((v >> 8) & 0xFF) | ((v & 0xFF) << 8)  # back to native for debug
        r = (le >> 11) & 0x1F
        g = (le >> 5) & 0x3F
        b = le & 0x1F
        print(f"  pal[{idx:3d}] = 0x{v:04x}  R={r*8:3d} G={g*4:3d} B={b*8:3d}")

    # === Build header file ===
    lines = []
    lines.append("// Xevious color palettes - RGB565 (big-endian for SPI)")
    lines.append("// Generated by fix_xevious_colors.py")
    lines.append("// Based on verified MAME xevious_vh_convert_color_prom")
    lines.append("// Palette: 128 colors from xvi-8.6a/9.6d/10.6e")
    lines.append("// BG: xvi-7.4h (low) + xvi-6.4f (high)")
    lines.append("// Sprites: xvi-4.3l (low) + xvi-5.3m (high), bit7=visible")
    lines.append("// FG: direct group->palette mapping (no PROM lookup)")
    lines.append("")

    # Master palette (for reference, not used at runtime)
    lines.append("const unsigned short xevious_palette[128] = {")
    for i in range(0, 128, 16):
        chunk = palette[i:i+16]
        lines.append("  " + ",".join(f"0x{c:04x}" for c in chunk) + ",")
    lines.append("};")
    lines.append("")

    # === FG char colors: 64 groups x 4 colors ===
    # MAME: NO PROM lookup. color_group directly indexes palette.
    # Pixel 0 = transparent, pixels 1/2/3 = palette[color_group]
    lines.append("// FG char colors: 64 groups x 4 colors")
    lines.append("// MAME: direct mapping, group k -> palette[k] (no PROM lookup)")
    lines.append("const unsigned short xevious_cmap_fg[64][4] = {")
    for group in range(64):
        color = palette[group]  # direct: color_group -> palette[group]
        color_str = f"0x0000,0x{color:04x},0x{color:04x},0x{color:04x}"
        comma = "," if group < 63 else ""
        lines.append(f"  {{{color_str}}}{comma}")
    lines.append("};")
    lines.append("")

    # Print some FG samples
    print("\n=== FG char color samples ===")
    for g in [0, 1, 2, 3, 4, 5, 10, 20, 30, 63]:
        c = palette[g]
        le = ((c >> 8) & 0xFF) | ((c & 0xFF) << 8)
        r = (le >> 11) & 0x1F
        gv = (le >> 5) & 0x3F
        b = le & 0x1F
        print(f"  fg[{g:2d}] = 0x{c:04x}  R={r*8:3d} G={gv*4:3d} B={b*8:3d}")

    # === Sprite colors: 64 groups x 8 colors (3bpp) ===
    # MAME: c = (xvi-4.3l[i] & 0x0F) | ((xvi-5.3m[i] & 0x0F) << 4)
    #   if (c & 0x80) -> visible, palette[c & 0x7F]
    #   else -> transparent (color 0x80 = black)
    # 3bpp sprites: 8 pixel values (0-7) per group
    lines.append("// Sprite colors: 64 groups x 8 colors (3bpp)")
    lines.append("// MAME: (xvi-4.3l & 0xF) | ((xvi-5.3m & 0xF)<<4), bit7=visible")
    lines.append("const unsigned short xevious_cmap_sprites[64][8] = {")
    for group in range(64):
        colors = []
        for pixel in range(8):
            idx = group * 8 + pixel
            if idx < min(len(spr_lo), len(spr_hi)):
                c = (spr_lo[idx] & 0x0F) | ((spr_hi[idx] & 0x0F) << 4)
                if c & 0x80:
                    pal_idx = c & 0x7F
                    if pal_idx < 128:
                        colors.append(palette[pal_idx])
                    else:
                        colors.append(0)
                else:
                    colors.append(0)
            else:
                colors.append(0)
        color_str = ",".join(f"0x{c:04x}" for c in colors)
        comma = "," if group < 63 else ""
        lines.append(f"  {{{color_str}}}{comma}")
    lines.append("};")
    lines.append("")

    # Print some sprite samples
    print("\n=== Sprite color samples (3bpp, 8 entries per group) ===")
    for g in [0, 1, 2, 3, 4, 5, 10, 20, 30, 63]:
        for p in range(8):
            idx = g * 8 + p
            if idx < min(len(spr_lo), len(spr_hi)):
                c = (spr_lo[idx] & 0x0F) | ((spr_hi[idx] & 0x0F) << 4)
                vis = "VIS" if c & 0x80 else "TRN"
                pal = c & 0x7F
                print(f"  spr[{g:2d}][{p}] lookup=0x{c:02x} {vis} pal={pal}")

    # === BG tile colors: 128 groups x 4 colors ===
    # MAME: (xvi-7.4h[i] & 0x0F) | ((xvi-6.4f[i] & 0x0F) << 4) -> direct palette index
    lines.append("// BG tile colors: 128 groups x 4 colors")
    lines.append("// MAME: (xvi-7.4h[i] & 0xF) | ((xvi-6.4f[i] & 0xF) << 4)")
    lines.append("const unsigned short xevious_cmap_bg[128][4] = {")
    for group in range(128):
        colors = []
        for pixel in range(4):
            idx = group * 4 + pixel
            pal_idx = (bg_lo[idx] & 0x0F) | ((bg_hi[idx] & 0x0F) << 4)
            # Mask to 128 colors (values > 127 wrap)
            pal_idx &= 0x7F
            colors.append(palette[pal_idx])
        color_str = ",".join(f"0x{c:04x}" for c in colors)
        comma = "," if group < 127 else ""
        lines.append(f"  {{{color_str}}}{comma}")
    lines.append("};")
    lines.append("")

    # Print some BG samples
    print("\n=== BG tile color samples ===")
    for g in [0, 1, 2, 3, 10, 20, 50, 100, 127]:
        for p in range(4):
            idx = g * 4 + p
            pal_idx = (bg_lo[idx] & 0x0F) | ((bg_hi[idx] & 0x0F) << 4)
            print(f"  bg[{g:3d}][{p}] lo=0x{bg_lo[idx]:02x} hi=0x{bg_hi[idx]:02x} pal_idx=0x{pal_idx:02x}({pal_idx & 0x7f})")

    cmap_path = os.path.join(HDR_DIR, "xevious_cmap.h")
    with open(cmap_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nWritten: {cmap_path}")

    # === Generate xevious_sr3.h ===
    sr3_lines = []
    sr3_lines.append("#ifndef XEVIOUS_SR3_H")
    sr3_lines.append("#define XEVIOUS_SR3_H")
    sr3_lines.append("")
    sr3_lines.append("// Xevious sr3 PROM data (xvi-1.5n, 256 bytes)")
    sr3_lines.append("// Used by xevious_bb_r() for reads at CPU address 0xB800-0xB8FF")
    sr3_lines.append("const unsigned char xevious_sr3[256] PROGMEM = {")
    for i in range(0, 256, 16):
        chunk = sr3_data[i:i+16]
        sr3_lines.append("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    sr3_lines.append("};")
    sr3_lines.append("")
    sr3_lines.append("#endif")

    sr3_path = os.path.join(HDR_DIR, "xevious_sr3.h")
    with open(sr3_path, "w") as f:
        f.write("\n".join(sr3_lines) + "\n")
    print(f"Written: {sr3_path}")
    print("\nDone!")

if __name__ == "__main__":
    main()
